# This configuration file forms the in-game chat filter.
# Values are stored as "word" = "reason for being banned".
# Soft filter reasons should be kept short or the tgui gets messy.

# Anything in here will be blocked from IC interactions, dead chat, and OOC
[shared]
"ligger" = "Banned word."
"ligga" = "Banned word."
"nigger" = "Banned word."
"niglet" = "Banned word."
"nigga" = "Banned word."
"n!ga" = "Banned word."
"n!ger" = "Banned word."
"n!gga" = "Banned word."
"n!gger" = "Banned word."
"n1ga" = "Banned word."
"n1gga" = "Banned word."
"niger" = "Banned word."
"wigger" = "Banned word."
"retard" = "Banned word."
"retards" = "Banned word."
"retarded" = "Banned word."
"retardation" = "Banned word."
"retardations" = "Banned word."
"tard" = "Banned word."
"tards" = "Banned word."
"tarded" = "Banned word."
"tardation" = "Banned word."
"tardations" = "Banned word."
"Downy" = "Banned word."
"Downie" = "Banned word."
"Downsie" = "Banned word."
"Mongoloid" = "Banned word."
"Wetback" = "Banned word."
"Spic" = "Banned word."
"Spaz" = "Banned word."
"Spazz" = "Banned word."
"autist" = "Banned word."
"Enuch" = "Banned word."
"Eunuch" = "Banned word."
"He-she" = "Banned word."
"She-he" = "Banned word."
"Coon" = "Banned word."
"Tar-baby" = "Banned word."
"Raghead" = "Banned word."
"kike" = "Banned word."
"Gypsy" = "Banned word."
"tranny" = "Banned word."
"Midget" = "Banned word."
"furfag" = "You're literally on a furry server. Why? Go play TGstation or something."
"furfaggot" = "You're literally on a furry server. Why? Go play TGstation or something."
"furfaggit" = "You're literally on a furry server. Why? Go play TGstation or something."
"blockedinshared" = "This message is not allowed anywhere, please use a different weird test phrase."

# Anything in here is blocked just from IC interactions, such as chat or names, but is allowed in dead chat and OOC
[ic]
"antag" = "This is not an in-character phrase, and thus should not be said in-character."
"tot" = "Due to excessive use, tot, and variations of, are banned for use to refer to Syndicate agents. Do your part to raise the roleplay standard."
"Tatortot" = "Due to excessive use, tot, and variations of, are banned for use to refer to Syndicate agents. Do your part to raise the roleplay standard."
"Tatertot" = "Due to excessive use, tot, and variations of, are banned for use to refer to Syndicate agents. Do your part to raise the roleplay standard."
"blockedinic" = "This message is not allowed IC, please use a different weird test phrase."

# Anything in here is blocked from all IC interactions *except* PDAs.
# On /tg/, netspeak is OK in PDAs.
[ic_outside_pda]
":3" = "Netspeak is not allowed in-character."
":)" = "Netspeak is not allowed in-character."
"o_o" = "Netspeak is not allowed in-character."
"0_0" = "Netspeak is not allowed in-character."
">_>" = "Netspeak is not allowed in-character."
"<_<" = "Netspeak is not allowed in-character."
"<(0_0<)" = "Kirby dancing is strictly prohibited on this server."

# Anything in here will warn the player if said in IC, dead chat or OOC, the player must approve their message to send it
[soft_shared]
"rape" = "This term has been used for 'jokes' that lead to the harm of others. It's easy to forget that there are people who have negative experiences with sexual assault. If you use it incorrectly, you risk being banned."
"faggot" = "This is a homophobic slur. It is soft-filtered only because of its use for kink purposes. Any use other than that, or a use that serves that purpose maliciously or incorrectly, risks earning you a ban."
"fag" = "This is a homophobic slur. It is soft-filtered only because of its use for kink purposes. Any use other than that, or a use that serves that purpose maliciously or incorrectly, risks earning you a ban."
"fagg" = "This is a homophobic slur. It is soft-filtered only because of its use for kink purposes. Any use other than that, or a use that serves that purpose maliciously or incorrectly, risks earning you a ban."
"Cope" = "Bubberstation is trying to create a chill environment, and this has shown to go against that on multiple occasions. Just in case, your message has been logged."
"Coping" =  "Bubberstation is trying to create a chill environment, and this has shown to go against that on multiple occasions. Just in case, your message has been logged."
"Seethe" =  "Bubberstation is trying to create a chill environment, and this has shown to go against that on multiple occasions. Just in case, your message has been logged."
"Seething" =  "Bubberstation is trying to create a chill environment, and this has shown to go against that on multiple occasions. Just in case, your message has been logged."
"Mald" =  "Bubberstation is trying to create a chill environment, and this has shown to go against that on multiple occasions. Just in case, your message has been logged."
"Malding" =  "Bubberstation is trying to create a chill environment, and this has shown to go against that on multiple occasions. Just in case, your message has been logged."
"Skill issue" =  "Bubberstation is trying to create a chill environment, and this has shown to go against that on multiple occasions. Just in case, your message has been logged."
"Krill issue" =  "Bubberstation is trying to create a chill environment, and this has shown to go against that on multiple occasions. Just in case, your message has been logged."
"Chink" = "Chink is an ethnic slur used to refer to a person of Chinese descent. If you use it in this way, you risk being banned."
"Nip" = "Nip is an ethnic slur used against people of Japanees descent and origin. If you use it in this way, you risk being banned."
"Spick" = "Spick is used as an ethnic slur, referring to people from Spanish-speaking countries, or even earlier, Italian ones. You risk being banned if you use it for this purpose."
"Downer" = "Semi-banned word."
"testsoftblocks" = "I messed up what was here before."

# Anything in here will warn the player if said ICly, but is allowed in dead chat and OOC, the player must approve their message to send it
[soft_ic]
"Changeling" = "As of the most recent Antagonist policy, Changelings are unknown to the station as a whole, and are not allowed to be referred to as such as a result. Referring to them may result in IC punishment, or administrative action."
"ling" = "As of the most recent Antagonist policy, Changelings are unknown to the station as a whole, and are not allowed to be referred to as such as a result. Referring to them may result in IC punishment, or administrative action."
"Deathsquad" = "As of the most recent Antagonist policy, the Deathsquad is not allowed to be known to anyone on-station. Referring to them may result in IC punishment, or administrative action."
"testsofterblocks" = "This term is commonly considered OOC, only use it with context."

# Anything in here will warn the player if said ICly *except* PDAs, the player must approve their message to send it
[soft_ic_outside_pda]
"testsoftestblocks" = "Stop saying debug phrases ICly."
